communitys/urls.py
from django.urls import path
from .views import *

app_name = 'community'

urlpatterns = [
    path('', community_list, name='community_list'),
    path('create/', create_community, name='create_community'),
    path('<str:name>/', community_detail, name='detail'),



    path('edit/<int:community_id>/', edit_community, name='edit_community'),
    path('create_blog/<int:community_id>/', create_post_community, name ='create_blog'),

    path('<str:username>/like/', handle_like_view, name='handle_like'),

]

profiles/urls.py
from django.urls import path
from . import views


app_name = 'profiles'


urlpatterns = [
    path('<str:username>/', views.profile, name='profile'),

    path('<str:username>/friends/', views.friends, name='friends'),
    path('<str:username>/subscribers/', views.subscribers, name='subscribers'),
    path('<str:username>/subscriptions/', views.subscriptions, name='subscriptions'),

    path('<str:username>/add_friend/', views.add_friend, name='add_friend'),
    path('<str:username>/remove_friend/', views.remove_friend, name='remove_friend'),

    path('<str:username>/edit/', views.edit_profile, name='edit_profile'),
    path('<str:username>/edit_post/', views.edit_post, name='edit_post'),
    path('delete-blog/<int:blog_id>/', views.delete_blog, name='delete_blog'),


    path('<str:username>/news/', views.news_list, name='news'),
    path('<str:username>/like/', views.handle_like_view, name='handle_like'),
    path('<str:username>/handle_toggle',views.handle_toggle, name='handle_toggle'),

    path('<str:username>/subscribe/', views.subscribe, name='subscribe'),
    path('<str:username>/unsubscribe/', views.unsubscribe, name='unsubscribe'),
]

sait/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls')),
    path('messages/', include('mechat.urls')),
    path('music/', include('music.urls')),
    path('video/', include('video.urls')),
    path('communities/', include('communitys.urls')),
    path('', include('relog.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.shortcuts import redirect


class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    years = models.IntegerField(default=18)
    city = models.CharField(max_length=100, default='Не указано')
    status = models.CharField(max_length=100, default='Не указано')
    about_user = models.TextField(default='Не указано')

    friends = models.ManyToManyField(User, related_name='friends', blank=True)
    subscribers = models.ManyToManyField(User, related_name='subscribers', blank=True)
    subscriptions = models.ManyToManyField(User, related_name='subscriptions', blank=True)

    def __str__(self):
        return self.user.username


class BlogUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    likes = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images/')
    liked_users = models.ManyToManyField(User, related_name='liked_posts', blank=True)

    @staticmethod
    def handle_like(request, post_id, action, user, username):
        post = BlogUser.objects.get(id=post_id)
        print(request, post_id, action, user, username)
        if action == 'like':
            post.likes += 1
            post.liked_users.add(user)
        elif action == 'unlike':
            post.likes -= 1
            post.liked_users.remove(user)
        post.save()

        return redirect('profiles:profile', username=username)

    def __str__(self):
        return self.user.username

profiles/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import UserProfile, BlogUser
from communitys.models import BlogCommunity

@login_required
def profile(request, username):
    user_info = UserProfile.objects.get(user__username=username)
    current_user = request.user
    is_subscribed = user_info.subscribers.filter(id=current_user.id).exists()

    blog = BlogUser.objects.filter(user__username=username).order_by('-date')
    return render(request, 'profile/profile.html', {'username': username,
                                                    'user': current_user,
                                                    'user_info': user_info,
                                                    'blog': blog,
                                                    'is_subscribed': is_subscribed})


@login_required
def subscribe(request, username):
    if request.method == 'POST':
        user_info = UserProfile.objects.get(user__username=username)
        current_user = request.user
        current_user_info = UserProfile.objects.get(user__username=request.user.username)
        print(user_info, current_user_info, current_user)

        user_info.subscribers.add(current_user)
        current_user_info.subscriptions.add(user_info.user)

        return redirect(request.META['HTTP_REFERER'])


@login_required
def unsubscribe(request, username):
    if request.method == 'POST':
        user_info = UserProfile.objects.get(user__username=username)
        current_user = request.user
        current_user_info = UserProfile.objects.get(user__username=request.user.username)

        user_info.subscribers.remove(current_user)
        current_user_info.subscriptions.remove(user_info.user)

        return redirect(request.META['HTTP_REFERER'])


def handle_like_view(request, username):
    if request.method == 'POST':
        post_id = request.POST['post_id']
        action = request.POST['action']
        user = User.objects.get(username=username)
        BlogUser.handle_like(request, post_id, action, user, username)

    # Получите URL текущей страницы
    referer = request.META.get('HTTP_REFERER')
    if referer:
        # Добавьте якорь к URL страницы
        return redirect(referer + '#post-' + post_id)

    return redirect(request.META.get('HTTP_REFERER'))

def edit_profile(request, username):
    if request.method == 'POST':
        photo = request.FILES.get('photo')
        years = request.POST['years']
        city = request.POST['city']
        status = request.POST['status']
        about_user = request.POST['about_user']

        user_profile, created = UserProfile.objects.get_or_create(user=User.objects.get(username=username))
        if photo:
            user_profile.image = photo
        if years:
            user_profile.years = years
        if city:
            user_profile.city = city
        if status:
            user_profile.status = status
        if about_user:
            user_profile.about_user = about_user

        user_profile.save()

        return redirect(f'/profile/{username}/')

    return render(request, 'profile/edit_profile.html')


def edit_post(request, username):
    if request.method == 'POST':
        title = request.POST['title']
        photo = request.FILES.get('photo')
        if title.strip() != '':
            post = BlogUser.objects.create(user=User.objects.get(username=username), title=title)
            if photo:
                post.image = photo
                post.save()
            return redirect(f'/profile/{username}/')
    return render(request, 'profile/edit_post.html')


def news_list(request, username):
    user_info = UserProfile.objects.all()
    news = BlogUser.objects.all().order_by('-date')
    news_community = BlogCommunity.objects.all().order_by('-date')

    return render(request, 'profile/news.html', {'news': news,
                                                 'news_community': news_community,
                                                 'user_info': user_info})


def handle_toggle(request, username):
    toggle_status = request.session.get('news_toggle', 'user')

    if toggle_status == 'user':
        request.session['news_toggle'] = 'community'
    elif toggle_status == 'community':
        request.session['news_toggle'] = 'user'

    return redirect('profiles:news', username=username)


@login_required
def friends(request, username):
    all_user_info = UserProfile.objects.all()
    user_info = UserProfile.objects.get(user__username=username)
    friends = user_info.friends.all()
    return render(request, 'profile/friends/friends.html', {'username': username,
                                                            'friends': friends,
                                                            'user_info': user_info,
                                                            'all_user_info': all_user_info})


@login_required
def subscribers(request, username):
    all_user_info = UserProfile.objects.all()
    user_info = UserProfile.objects.get(user__username=username)
    subscribers = user_info.subscribers.all()
    return render(request, 'profile/friends/subscribers.html', {'username': username,
                                                                'subscribers': subscribers,
                                                                'user_info': user_info,
                                                                'all_user_info': all_user_info})


@login_required
def subscriptions(request, username):
    all_user_info = UserProfile.objects.all()
    user_info = UserProfile.objects.get(user__username=username)
    subscriptions = user_info.subscriptions.all()
    return render(request, 'profile/friends/subscriptions.html', {'username': username,
                                                                  'subscriptions': subscriptions,
                                                                  'user_info': user_info,
                                                                  'all_user_info': all_user_info})

@login_required
def add_friend(request, username):
    user_info = UserProfile.objects.get(user__username=username)
    current_user = request.user
    current_user_info = UserProfile.objects.get(user__username=current_user.username)

    user_info.friends.add(current_user)
    current_user_info.friends.add(user_info.user)

    user_info.subscribers.remove(current_user)
    current_user_info.subscriptions.remove(user_info.user)

    return redirect(request.META['HTTP_REFERER'])

def remove_friend(request, username):

    user_info = UserProfile.objects.get(user__username=username)
    current_user = request.user
    current_user_info = UserProfile.objects.get(user__username=current_user.username)

    user_info.friends.remove(current_user)
    current_user_info.friends.remove(user_info.user)

    user_info.subscribers.add(current_user)
    current_user_info.subscriptions.add(user_info.user)

    return redirect(request.META['HTTP_REFERER'])



def delete_blog(request, blog_id):
    blog = BlogUser.objects.get(id=blog_id)
    if blog.user == request.user:
        blog.delete()
    return redirect('profiles:profile', username=request.user.username)

templates/profile/edit_post.html
  {% extends 'base_profile.html' %}

  {% block title %}создание поста{% endblock %}
  {% block content %}
      <h2>Что вы хотите выставить?</h2>
  <form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-floating">
    <input type="text" class="form-control" id="floatingPassword" name="title" placeholder="title">
    <label for="floatingInput">title</label>
  </div>

  <div class="form-floating">
    <input type="file" class="form-control" id="floatingPhoto" name="photo">
    <label for="floatingPhoto">photo</label>
  </div>

  <button type="submit">Сохранить</button>
</form>
  {% endblock %}

templates/profile/edit_profile.html
{% extends 'base_profile.html' %}

{% block title %}Редактирование профиля{% endblock %}

<style>
  edit {
  margin-right: 100px;
}


</style>


{% block content %}
  <h2>Редактирование профиля</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
      <div class="form-floating">
        <input type="text" class="form-control" id="years" name="years" placeholder="years">
        <label for="years">years</label>
      </div>

      <div class="form-floating">
        <input type="text" class="form-control" id="city" name="city" placeholder="city">
        <label for="city">city</label>
      </div>

      <div class="form-floating">
        <input type="text" class="form-control" id="status" name="status" placeholder="status">
        <label for="status">status</label>
      </div>

      <div class="form-floating">
        <input type="text" class="form-control" id="about_user" name="about_user" placeholder="about_user">
        <label for="about_user">about user</label>
      </div>

      <div class="form-floating">
        <input type="file" class="form-control" id="floatingPhoto" name="photo">
        <label for="floatingPhoto">photo</label>
      </div>
    <button type="submit">Сохранить</button>
  </form>

{% endblock %}

templates/profile/news.html
  {% extends 'base_profile.html' %}

  {% block title %}Новости{% endblock %}

  {% block content %}


    <div>
    <button class="btn btn-primary" onclick="location.href='{% url 'profiles:handle_toggle' username=request.user.username %}'">
        {% if request.session.news_toggle == 'user' %}
            Блог сообществ
        {% else %}
            Блог пользователей
        {% endif %}
    </button>
    </div>



{% if request.session.news_toggle == 'user' %}
      {% for new in news %}
        <div class="blog" id="post-{{ new.id }}">
            {% for user_info_item in user_info %}
                {% if user_info_item.user == new.user %}
                    <a href="/profile/{{ new.user }}/" class="align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
                        <img src="{{ user_info_item.image.url }}" alt="Post Image" width="50" height="50" style="border-radius: 50%;">
                        <span class="fs-4">{{ new.user }}</span>
                    </a>
                {% endif %}
            {% endfor %}

            <h6>{{ new.title }}</h6>

            {% if new.image %}
                <img src="{{ new.image.url }}" alt="Post Image" width="400" height="400" style="border-radius: 10%;">
            {% endif %}
            <p>likes: {{ new.likes }}</p>
            <p>date - {{ new.date }}</p>

            <form method="post" action="{% url 'profiles:handle_like' username=request.user.username %}">
                {% csrf_token %}
                <input type="hidden" name="post_id" value="{{ new.id }}">
                {% if request.user in new.liked_users.all %}
                    <button type="submit" name="action" value="unlike" class="btn btn-primary rounded-pill px-3">Unlike</button>
                {% else %}
                    <button type="submit" name="action" value="like" class="btn btn-primary rounded-pill px-3">Like</button>
                {% endif %}
            </form>
        </div>


  <br><br>
      {% endfor %}







  {% else %}
    {% for new in news_community %}
        <div class="blog" id="post-{{ new.id }}">
            {% for user in user_info %}
                {% if user.user == new.user %}
                    <a href="/profile/{{ new.user }}/" class="align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
                        <img src="{{ user.image.url }}" alt="Post Image" width="50" height="50" style="border-radius: 50%;">
                        <span class="fs-4">{{ new.user }}</span>
                    </a>
                {% endif %}
            {% endfor %}

            <h6>{{ new.title }}</h6>

            {% if new.image %}
                <img src="{{ new.image.url }}" alt="Post Image" width="400" height="400" style="border-radius: 10%;">
            {% endif %}
            <p>likes: {{ new.likes }}</p>
            <p>date - {{ new.date }}</p>
                <form method="post" action="{% url 'community:handle_like' username=new.community.name %}">

                {% csrf_token %}
                <input type="hidden" name="post_id" value="{{ new.id }}">
                {% if user in new.liked_users.all %}
                    <button type="submit" name="action" value="unlike" class="btn btn-primary rounded-pill px-3">Unlike</button>
                {% else %}
                    <button type="submit" name="action" value="like" class="btn btn-primary rounded-pill px-3">Like</button>
                {% endif %}
                </form>
            </div>




    {% endfor %}
{% endif %}



  {% endblock %}

templates/profile/profile.html
{% extends 'base_profile.html' %}

{% block title %}{{ user.username}}{% endblock %}
{% block content %}

{% load static %}


<style>
    .user_information {
        padding: 5px;
    }
</style>





<h1>{{ username }}</h1>
<div class="d-flex  p-3 my-3  bg-purple rounded shadow-sm">
{% if user_info.image %}
  <div>
        <img src="{{ user_info.image.url }}" alt="Post Image" width="200" height="200" style="border-radius: 50%;">
    </div>
{% endif %}
<div class="user_information">
    <h6> Город - {{ user_info.city }}</h6>
    <h6> Лет - {{ user_info.years }}</h6>
    <h6> Статус - {{ user_info.status }}</h6>
    <h6> Информация обо мне - {{ user_info.about_user }}</h6>
    <h6> <a href="{% url 'profiles:friends' username=username %} ">Друзей</a> - {{ user_info.friends.count }}</h6>


    {% if user != user_info.user %}
        {% if is_subscribed %}
            <h3><a href="{% url 'messages' username=user_info.user.username %}" >Написать</a> </h3>

            <form method="post" action="{% url 'profiles:unsubscribe' username=username %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary" data-username="{{ username }}">Отписаться</button>
            </form>
        {% else %}
            <form method="post" action="{% url 'profiles:subscribe' username=username %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary" data-username="{{ username }}">Подписаться</button>
            </form>
        {% endif %}
    {% endif %}



</div>
</div>







{% for b in blog %}
<div class="blog" id="post-{{ b.id }}">


    <a href="#" class=" align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <img src="{{ user_info.image.url }}" alt="Post Image" width="50" height="50" style="border-radius: 50%;">
        <span class="fs-4">{{ b.user }}</span>
    </a>

    <h6>{{ b.title }}</h6>

    {% if b.image %}
        <img src="{{ b.image.url }}" alt="Post Image" width="400" height="400" style="border-radius: 10%;">
    {% endif %}
    <p>likes: {{ b.likes }}</p>
    <p>date - {{ b.date }}</p>
    <form method="post" action="{% url 'profiles:handle_like' username=request.user %}">

        {% csrf_token %}
        <input type="hidden" name="post_id" value="{{ b.id }}">
        {% if user in b.liked_users.all %}
            <button type="submit" name="action" value="unlike" class="btn btn-primary rounded-pill px-3">Unlike</button>
        {% else %}
            <button type="submit" name="action" value="like" class="btn btn-primary rounded-pill px-3">Like</button>
        {% endif %}
    </form>

    {% if user == b.user %}
        <form method="post" action="{% url 'profiles:delete_blog' blog_id=b.id %}" id="delete-form">
            {% csrf_token %}
            <button type="button" class="btn btn-danger rounded-pill px-3" onclick="showConfirmModal()">Delete</button>
        </form>
    {% endif %}

    <!-- Модальное окно подтверждения -->
    <div class="modal fade" id="confirm-modal" tabindex="-1" role="dialog" aria-labelledby="confirm-modal-label" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="confirm-modal-label">Confirmation</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            Are you sure you want to delete this blog post?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            <button type="button" class="btn btn-danger" onclick="deleteBlog()">Yes</button>
          </div>
        </div>
      </div>
    </div>


    <br><br>
</div>


<script>
    function showConfirmModal() {
        $('#confirm-modal').modal('show');
    }

    function deleteBlog() {
        $('#delete-form').submit();
    }
</script>



{% endfor %}




  {% endblock %}