communitys/urls.py
from django.urls import path
from .views import *

app_name = 'community'

urlpatterns = [
    path('', community_list, name='community_list'),
    path('create/', create_community, name='create_community'),
    path('<str:name>/', community_detail, name='detail'),



    path('edit/<int:community_id>/', edit_community, name='edit_community'),
    path('create_blog/<int:community_id>/', create_post_community, name ='create_blog'),

    path('<str:username>/like/', handle_like_view, name='handle_like'),

]

sait/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls')),
    path('messages/', include('mechat.urls')),
    path('music/', include('music.urls')),
    path('video/', include('video.urls')),
    path('communities/', include('communitys.urls')),
    path('', include('relog.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

communitys/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import redirect


class Community(models.Model):
    creator = models.ForeignKey(User, related_name='creator', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField()
    members = models.ManyToManyField(User)

    def __str__(self):
        return self.name

class CommunityProfile(models.Model):
    community = models.ForeignKey(Community, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', blank=True, null=True)
    status = models.CharField(max_length=100, default='Не указано')
    about_community = models.TextField(default='Не указано')

    subscribers = models.ManyToManyField(User, related_name='subscribers_community', blank=True)

    def __str__(self):
        return self.community.name


class BlogCommunity(models.Model):
    community = models.ForeignKey(Community, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    likes = models.IntegerField(default=0)
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='images/')
    liked_users = models.ManyToManyField(User, related_name='liked_posts_community', blank=True)

    @staticmethod
    def handle_like(request, post_id, action, community, username):
        post = BlogCommunity.objects.get(id=post_id, community=community)
        if action == 'like':
            post.likes += 1
            post.liked_users.add(request.user)
        elif action == 'unlike':
            post.likes -= 1
            post.liked_users.remove(request.user)
        post.save()

        return redirect('community:detail', name=username)

    def __str__(self):
        return self.community.name

communitys/forms.py
from django import forms
from .models import Community,CommunityProfile,BlogCommunity

class CommunityForm(forms.ModelForm):
    class Meta:
        model = Community
        fields = ['name', 'description']

class CommunityProfileForm(forms.ModelForm):

    class Meta:
        model = CommunityProfile
        fields = ['image', 'status', 'about_community']


class BlogCommunityForm(forms.ModelForm):

    class Meta:
        model = BlogCommunity
        fields = ['title','image']

communitys/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import CommunityForm,CommunityProfileForm,BlogCommunityForm
from .models import Community,CommunityProfile,BlogCommunity


def community_list(request):
    communities = Community.objects.all()
    profiles_community = CommunityProfile.objects.all()
    return render(request, 'community/community_list.html', {'communities': communities,
                                                             'profiles_community':profiles_community})


def community_detail(request, name):
    community = get_object_or_404(Community, name=name)
    blog_community = BlogCommunity.objects.filter(community=community)
    profile_community = CommunityProfile.objects.get(community=community)

    return render(request, 'community/community.html', {'community': community,
                                                        'blog_community': blog_community,
                                                        'profile_community': profile_community})


def create_community(request):
    if request.method == 'POST':
        form = CommunityForm(request.POST)
        if form.is_valid():
            community = form.save(commit=False)
            community.creator = request.user

            # Проверка наличия модели с таким же именем
            existing_community = Community.objects.filter(name=community.name).exists()
            if existing_community:
                form.add_error('name', 'Сообщество с таким именем уже существует')
            else:
                community.save()
                community.members.add(request.user)
                CommunityProfile.objects.create(community=community)
                return redirect('community:community_list')
    else:
        form = CommunityForm()
    return render(request, 'community/create_community.html', {'form': form})


def edit_community(request, community_id):
    community_profile = get_object_or_404(CommunityProfile, community_id=community_id)
    if request.method == 'POST':
        form = CommunityProfileForm(request.POST, request.FILES, instance=community_profile)
        if form.is_valid():
            form.save()
            return redirect('community:community_list')
    else:
        form = CommunityProfileForm(instance=community_profile)
    return render(request, 'community/edit_community.html', {'form': form})


def create_post_community(request, community_id):
    community = get_object_or_404(Community, id=community_id)

    if request.method == 'POST':
        form = BlogCommunityForm(request.POST, request.FILES)
        if form.is_valid():
            blog = form.save(commit=False)
            blog.community = community
            blog.save()
            return redirect('community:detail', name = community.name)
    else:
        form = BlogCommunityForm()

    return render(request, 'community/create_post_community.html', {'form': form, 'community': community})

def handle_like_view(request, username):
    if request.method == 'POST':
        post_id = request.POST['post_id']
        action = request.POST['action']

        community = Community.objects.get(name=username)
        BlogCommunity.handle_like(request, post_id, action, community, username)


        referer = request.META.get('HTTP_REFERER')
        if referer:
            # Добавьте якорь к URL страницы
            return redirect(referer + '#post-' + post_id)


    return redirect(request.META['HTTP_REFERER'])

templates/community/community.html
{% extends 'base_profile.html' %}

{% block content %}

<h1>{{ profile_community.community }}</h1>
<div class="d-flex  p-3 my-3  bg-purple rounded shadow-sm">
    {% if profile_community.image %}
      <div>
        <img src="{{ profile_community.image.url }}" alt="Post Image" width="200" height="200" style="border-radius: 50%;">
      </div>
    {% endif %}
    <div class="user_information">
        <h6> Статус - {{ profile_community.status }}</h6>
        <h6> Информация обо мне - {{ profile_community.about_community }}</h6>
    </div>
    </div>
    {% if community.creator == request.user %}
        <a href="{% url 'community:edit_community' community_id=community.id %}">Редактировать сообщество</a>
    <br>
        <a href="{% url 'community:create_blog'  community_id=community.id %}">Создать пост</a>
    {% endif %}

<br>
{% for b in blog_community %}
<div class="blog">


    <a href="#" class=" align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <img src="{{ profile_community.image.url }}" alt="Post Image" width="50" height="50" style="border-radius: 50%;">
        <span class="fs-4">{{ b.community }}</span>
    </a>

    <h6>{{ b.title }}</h6>

    {% if b.image %}
        <img src="{{ b.image.url }}" alt="Post Image" width="400" height="400" style="border-radius: 10%;">
    {% endif %}
    <p>likes: {{ b.likes }}</p>
    <p>date - {{ b.date }}</p>
    <form method="post" action="{% url 'community:handle_like' username=b.community %}">

        {% csrf_token %}
        <input type="hidden" name="post_id" value="{{ b.id }}">
        {% if user in b.liked_users.all %}
            <button type="submit" name="action" value="unlike" class="btn btn-primary rounded-pill px-3">Unlike</button>
        {% else %}
            <button type="submit" name="action" value="like" class="btn btn-primary rounded-pill px-3">Like</button>
        {% endif %}
    </form>
    <br><br>
</div>
{% endfor %}

{% endblock %}

templates/community/community_list.html
{% extends 'base_profile.html' %}

{% block content %}


<style>
    /* Стили для сообщений */
    .message-container {
        background-color: #f5f5f5;
        padding: 10px;
        border: 1px solid #dddddd;
        margin-bottom: 10px;
    }

    .chat-link {
        color: #007bff;
        text-decoration: none;
    }
</style>

<a href="{% url 'community:create_community' %}">Создать сообщество</a>

<br><br>
<div class="message-container">
    {% for community in communities %}
        {% for profile_community in profiles_community %}
            {% if profile_community.community == community %}
                <div class="row">
                    <div class="col-2">
                        {% if profile_community.image %}
                            <img src="{{ profile_community.image.url }}" alt="Post Image" width="50" height="50" style="border-radius: 50%;">
                        {% endif %}
                    </div>
                    <div class="col-10">
                        <a href="{{ community.name }}/">{{ community.name }}</a>
                        <h6>создатель - {{ community.creator }}</h6>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endfor %}
</div>


{% endblock %}

templates/community/create_community.html
{% extends 'base_profile.html' %}

{% block content %}


<h1>Create Community</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Create</button>
</form>

{% endblock %}

templates/community/create_post_community.html
{% extends 'base_profile.html' %}
{% block content %}
  <h2>Create New Blog</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
  </form>
  <p>Community: {{ community.name }}</p>
{% endblock content %}

templates/community/edit_community.html
{% extends 'base_profile.html' %}

{% block content %}




<h1>Edit Community</h1>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}

  {{ form.as_p }}

  <input type="submit" value="Save">
</form>


{% endblock %}