sait/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls')),
    path('messages/', include('mechat.urls')),
    path('music/', include('music.urls')),
    path('video/', include('video.urls')),
    path('communities/', include('communitys.urls')),
    path('', include('relog.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video/urls.py
from django.urls import path
from . import views

app_name = 'video'

urlpatterns = [
    path('', views.video_list, name='video_list'),
    path('add/', views.video_add, name='video_add'),
    path('user/', views.user_video, name='user_video'),
    path('user_add/<int:i>/', views.add_for_user_video, name='add_user_video'),
    path('user_delete/<int:i>/', views.delete_video, name='delete_user_video'),
]

video/models.py
from django.contrib.auth.models import User
from django.db import models


class Video(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    video_file = models.FileField(upload_to='videos')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class ProfileVideo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    video = models.ManyToManyField(Video, related_name='video',blank=True)

video/forms.py
from django import forms
from .models import Video

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ('title', 'description', 'video_file')

video/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from .models import Video, ProfileVideo
from .forms import VideoForm


def video_list(request):
    videos = Video.objects.order_by('-created_at')
    return render(request, 'video/video_list.html', {'videos': videos})


def video_add(request):
    if request.method == 'POST':
        form = VideoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('video:video_list')
    else:
        form = VideoForm()
    return render(request, 'video/video_add.html', {'form': form})


def user_video(request):
    try:
        user_info = ProfileVideo.objects.get(user=request.user)
    except:
        user_info = None
    return render(request, 'video/video_user.html', {'user_info': user_info})


def add_for_user_video(request, i):
    video = Video.objects.get(id=i)
    user_profile, created = ProfileVideo.objects.get_or_create(user=request.user)
    user_profile.video.add(video)
    user_profile.save()
    return redirect(request.META['HTTP_REFERER'])


def delete_video(request, i):
    video = Video.objects.get(id=i)
    user_profile = ProfileVideo.objects.get(user=request.user)
    user_profile.video.remove(video)
    user_profile.save()
    return redirect(request.META['HTTP_REFERER'])

templates/video/video_add.html
{% extends 'base_profile.html' %}

{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>


{% endblock %}

templates/video/video_list.html
{% extends 'base_profile.html' %}

{% block content %}

<a class='btn btn-primary' href="{% url 'video:video_add' %}">добавить видео</a>

<style>

    video {
      position: relative;
    width: 400px;
    height: 200px;
    margin: 0 auto;
    }


    .video-wrapper {
    position: relative;
    width: 50%;
    height: 50%;
    margin: 0 auto;
    }

    .video-title {
        font-size: 14px;
        text-align: center;
        margin-top: 8px;
    }
    .video-description {
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
        background-color: rgba(0, 0, 0, 0.7);
        color: #fff;
        padding: 8px;
        font-size: 12px;
    }

        .full-screen {
        width: 100%;
        height: 100vh;
        position: fixed;
        top: 0;
        left: 0;
        z-index: 9999;
        background-color: #000000;
    }

    .full-screen video {
        width: 50%;
        height: 50%;
    }
</style>

{% for video in videos %}
    <div class="video-wrapper">
        <h2 class="video-title">{{ video.title }}</h2>
        <video src="{{ video.video_file.url }}" controls onclick="toggleFullScreen(this)" onended="exitFullScreen(this)"></video>
        <br><br><br>
        <div class="video-description">{{ video.description }}</div>
    </div>
    <a href="{% url 'video:add_user_video' i=video.id %}">Добавить в мои видео</a>
{% empty %}
    <p>No videos available.</p>
{% endfor %}

<script>
    function toggleFullScreen(video) {
        video.classList.toggle("full-screen");
    }

    function exitFullScreen(video) {
        video.classList.remove("full-screen");
    }
</script>

{% endblock %}

templates/video/video_user.html
{% extends 'base_profile.html' %}

{% block content %}


<style>

    video {
      position: relative;
    width: 400px;
    height: 200px;
    margin: 0 auto;
    }


    .video-wrapper {
    position: relative;
    width: 50%;
    height: 50%;
    margin: 0 auto;
    }

    .video-title {
        font-size: 14px;
        text-align: center;
        margin-top: 8px;
    }
    .video-description {
        position: absolute;
        bottom: 0;
        left: 0;
        width: 100%;
        background-color: rgba(0, 0, 0, 0.7);
        color: #fff;
        padding: 8px;
        font-size: 12px;
    }

        .full-screen {
        width: 100%;
        height: 100vh;
        position: fixed;
        top: 0;
        left: 0;
        z-index: 9999;
        background-color: #000000;
    }

    .full-screen video {
        width: 50%;
        height: 50%;
    }
</style>




{% for video in user_info.video.all %}
    <div class="video-wrapper">
        <video src="{{ video.video_file.url }}" controls onclick="toggleFullScreen(this)" onended="exitFullScreen(this)"></video>
        <form method="POST" action="{% url 'video:delete_user_video' i=video.id %}">
            {% csrf_token %}
            <input type="submit" value="Delete">
        </form>
    </div>
{% endfor %}



<script>
    function toggleFullScreen(video) {
        video.classList.toggle("full-screen");
    }

    function exitFullScreen(video) {
        video.classList.remove("full-screen");
    }
</script>


{% endblock %}