communitys/urls.py
from django.urls import path
from .views import *

app_name = 'community'

urlpatterns = [
    path('', community_list, name='community_list'),
    path('create/', create_community, name='create_community'),
    path('<str:name>/', community_detail, name='detail'),



    path('edit/<int:community_id>/', edit_community, name='edit_community'),
    path('create_blog/<int:community_id>/', create_post_community, name ='create_blog'),

    path('<str:username>/like/', handle_like_view, name='handle_like'),

]

music/urls.py
from django.urls import path
from .views import song_list, song_upload, music_user, add_for_user_song, delete_song

app_name = 'music'

urlpatterns = [
    path('songs/', song_list, name='song_list'),
    path('upload/', song_upload, name='song_upload'),
    path('user/', music_user, name='music_user'),
    path('user_add/<int:i>/', add_for_user_song, name='add_user_song'),
    path('user_delete/<int:i>/', delete_song, name='delete_user_song'),
]

profiles/urls.py
from django.urls import path
from . import views


app_name = 'profiles'


urlpatterns = [
    path('<str:username>/', views.profile, name='profile'),

    path('<str:username>/friends/', views.friends, name='friends'),
    path('<str:username>/subscribers/', views.subscribers, name='subscribers'),
    path('<str:username>/subscriptions/', views.subscriptions, name='subscriptions'),

    path('<str:username>/add_friend/', views.add_friend, name='add_friend'),
    path('<str:username>/remove_friend/', views.remove_friend, name='remove_friend'),

    path('<str:username>/edit/', views.edit_profile, name='edit_profile'),
    path('<str:username>/edit_post/', views.edit_post, name='edit_post'),
    path('delete-blog/<int:blog_id>/', views.delete_blog, name='delete_blog'),


    path('<str:username>/news/', views.news_list, name='news'),
    path('<str:username>/like/', views.handle_like_view, name='handle_like'),
    path('<str:username>/handle_toggle',views.handle_toggle, name='handle_toggle'),

    path('<str:username>/subscribe/', views.subscribe, name='subscribe'),
    path('<str:username>/unsubscribe/', views.unsubscribe, name='unsubscribe'),
]

sait/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('profiles.urls')),
    path('messages/', include('mechat.urls')),
    path('music/', include('music.urls')),
    path('video/', include('video.urls')),
    path('communities/', include('communitys.urls')),
    path('', include('relog.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video/urls.py
from django.urls import path
from . import views

app_name = 'video'

urlpatterns = [
    path('', views.video_list, name='video_list'),
    path('add/', views.video_add, name='video_add'),
    path('user/', views.user_video, name='user_video'),
    path('user_add/<int:i>/', views.add_for_user_video, name='add_user_video'),
    path('user_delete/<int:i>/', views.delete_video, name='delete_user_video'),
]

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <link rel="icon" href="/media/images/icon.png">

    <title>{% block title %}Мой сайт{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="icon" href="/media/images/icon.png">

    <script src="https://www.google.com/recaptcha/enterprise.js?render=6Lcet0gpAAAAAGy4SZMjZSuGYjKC693HRe2tgvow"></script>


</head>

<body>
    <header>
    <div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <img class="mb-4" src="https://cdn-icons-png.flaticon.com/128/29/29662.png" alt="" width="72" height="57">
        <span class="fs-4">ReloS</span>
      </a>

      <ul class="nav nav-pills">
          {% for menu in menus %}
            <li class="nav-item"><a href="/{{ menu.title }}/" class="nav-link">{{menu.title}}</a></li>
          {% endfor %}
      </ul>
    </header>
    </div>
    </header>

    <main>
        {% block content %}

        {% endblock %}
    </main>

    <footer class="pt-5 my-5 text-body-secondary border-top">
    Created by the Akilo · © 2023
  </footer>


<script>
  function onClick(e) {
    e.preventDefault();
    grecaptcha.enterprise.ready(async () => {
      const token = await grecaptcha.enterprise.execute('6Lcet0gpAAAAAGy4SZMjZSuGYjKC693HRe2tgvow', {action: 'LOGIN'});
    });
  }
</script>

</body>
</html>

templates/base_profile.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>{% block title %}Мой сайт{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="icon" href="/media/images/icon.png">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</head>

<body>

<style>
        .video-wrapper {
            position: relative;
            width: <ширина видео>;
        }
        .video-title {
            font-size: 14px;
            text-align: center;
            margin-top: 8px;
        }
        .video-description {
            position: absolute;
            bottom: 0;
            left: 0;
            width: 100%;
            background-color: rgba(0, 0, 0, 0.7);
            color: #fff;
            padding: 8px;
            font-size: 12px;
        }


            .sidebar {
        margin-top: 70px;
        position: fixed;
        top: 0;
        left: 0;
        height: 100vh;
        width: 280px;
        background-color: #fff;
        display: flex;
        flex-direction: column;
        box-shadow: 0 30px 30px rgba(0.5, 0.5, 0.5, 0.2);
        z-index: 1;
    }

    .sidebar ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
    }

    .sidebar ul li {
        padding: 10px;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }

    .sidebar a {
        display: block;
        color: #222;
        text-decoration: none;
    }

    .sidebar .active {
        background-color: #ebebeb;
    }

    .sidebar .logout {
        position: absolute;
        margin-bottom: 100px;
        bottom: 10px;
        left: 10px;
    }

    .sidebar img {
        margin: 10px;
    }

    .sidebar .profile-link {
        font-weight: bold;
        font-size: 18px;
        margin-bottom: 20px;
        color: #222;
    }



        .sidebar2 {
            margin-top: 70px;
            position: fixed;
            top: 0;
            right: 0;
        height: 100vh;
        width: 280px;
        background-color: #fff;
        display: flex;
        flex-direction: column;
        box-shadow: 0 30px 30px rgba(0.5, 0.5, 0.5, 0.2);
        z-index: 1;
        }
        .sidebar2 ul li {
            padding: 10px;
            text-align: center;
        }
        .sidebar2 a {
            color: #000;
            text-decoration: none;
            border-bottom: 1px solid #000;
        }

        .sidebar2 .active {
            background-color: transparent;
        }
        .sidebar2 .logout {
            position: absolute;
            bottom: 10px;
            left: 10px;
        }
        .main-content {
            margin-left: 280px;
            margin-right: 280px;
            padding: 20px;
            z-index: 0;
        }
        .d-flex.align-items-center.p-3.my-3.bg-purple.rounded.shadow-sm {
            justify-content: center;
        }
        .blog {
            margin-left: 220px;
        }
        .music-menu {
          position: fixed;
          margin-top: 5px;
          top: 0;
          left: 0;
          height: 70px;
          width: 100%;
          color: #ffffff;
          box-shadow: 0 30px 30px rgba(0.5, 0.5, 0.5, 0.2);
          z-index: 1;
          display: flex;
          align-items: center;
          justify-content: center; /* Update this line to center align */
        }

        .music-menu ul {
          list-style: none;
          display: flex;
          align-items: center;
          justify-content: space-around; /* Update this line to evenly space */
          margin: 0;
          padding: 0;
          width: 60%; /* Added this line */
        }

        .music-menu li {
          margin: 0;
          width: 50%; /* Added this line */
          text-align: center; /* Add this line for center aligning text */
        }
        .music-menu a {
            color: #000;
            text-decoration: none;
            border-bottom: 1px solid #000;
        }

        .music-menu a:hover {
            color: #000;
            text-decoration: underline;
        }

    </style>



<body>
    <div class="container">
        <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
            <div class="row">
                <div class="music-menu">
                    <ul>
                        <li><a href="{% url 'music:song_list' %}">музыка</a></li>
                        <li><a  href="{% url 'video:video_list' %}">видео</a></li>
                    </ul>
                </div>


    <div class="sidebar">
    <div class="d-flex align-items-center p-3 my-3 bg-purple rounded shadow-sm">
        <img src="/media/images/icon.png" alt="" width="100" height="100">
    </div>

    <div class="d-flex align-items-center p-3 my-3 bg-purple rounded shadow-sm">
        <ul>
            <li class="profile-link"><a href="{% url 'profiles:profile' username=user.username %}">Моя страница</a></li>
            <li><a href="{% url 'profiles:news' username=user.username %}">Новости</a></li>
            <li><a href="/messages/{{request.user}}/">Чат</a></li>
            <li><a href="{% url 'video:user_video' %}">Мои видео</a></li>
            <li><a href="{% url 'music:music_user' %}">Мои аудиозаписи</a></li>
            <li><a href="{% url 'community:community_list' %}">Сообщества</a></li>
        </ul>
    </div>
    <a class="logout" href="/logout/">Выйти</a>

</div>



      <div class="sidebar2">
      <div class="d-flex align-items-center p-3 my-3 bg-purple rounded shadow-sm">
        <ul>
        <li><a href="{% url 'profiles:edit_profile' username=user.username %}">Редактировать профиль</a></li>
        <li><a href="{% url 'profiles:edit_post' username=user.username %}">Создать пост</a></li>
      </ul>
      </div>
      </div>

    </div>

        </header>

        </div>

        <main>
          <div class="main-content">
            {% block content %}

            {% endblock %}
          </div>
        </main>

        <footer class="pt-5 my-5 text-body-secondary border-top">
        Created by the Akilo · © 2023
      </footer>



</body>
</html>